swagger: "2.0"

info:
  version: "1.0.2"
  title: "Orders microservice"

paths:
  /user_mark:
    get:
      summary: "Get user mark"
      parameters:
      - in: "body"
        name: "body"
        description: "User id to count user mark by it"
        required: true
        schema:
          $ref: "#/definitions/UserMark"
      responses:
        "200":
          description: "Request ok"
        "400":
          description: "Orders not found"

  /order/complete:
    post:
      summary: "Fill data about completed order"
      parameters:
      - in: "body"
        name: "body"
        description: "Completed order object"
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        "200":
          description: "Request ok"
        "400":
          description: "Order not found"

definitions:
  UserMark:
    type: "object"
    properties:
      userid:
        type: "integer"
        format: "int64"
  Order:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      other_order_fields:
        type: "string"
      passenger_mark:
        type: "integer"
        format: "int64"
        description: "user status"
